version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: expense_app
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: expense_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: expense_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: expense
      MYSQL_USER: expense
      MYSQL_PASSWORD: expense
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
